# Generated by Django 5.2 on 2025-04-15 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='publicade',
            new_name='publicado',
        ),
    ]
